### ISSUE TITLE
Plugin not working with latest Sketch version

### ISSUE THREAD

**Issue by Nummer5lebt** [mathieudutour/import-svg-as-artboard#18]
My loved plugin is not working with latest sketch update Version 85.1 (141321).

**Comment by groenroos** [comment]
I have the same problem - no error message or anything.

**Comment by pixelpanik** [comment]
Sketch DevTools gives the following error:

`MOJavaScriptException: TypeError: s.graph().width is not a function. (In 's.graph().width()', 's.graph().width' is undefined)
my-command.js:37:706
forEach [native code]
my-command.js:13:1155
my-command.js:37:305
__skpm_run my-command.js:45:121
__skpm_run [native code]`

Would be lovely if someone can fix this. Thanks in advance!

**Comment by jazzybeat** [comment]
I tried in v92 with no luck. I would love to have this plugin back. It was very useful when importing icons.

**Comment by ErwinOtten** [comment]
I would also love to have this feature back. Does anyone has an alternative solution?

**Comment by ErwinOtten** [comment]
Workaround here: https://github.com/ErwinOtten/import-svg-as-artboard. Requires manual input for desired artboard width and height.

**Comment by MoSyz** [comment]
Sadly, it does not work for 94.1 :( 
Please fix this needed plugin.

**Comment by mathieudutour** [comment]
happy to accept a PR that fixes it

**Comment by mathieudutour** [comment]
Fixed by #23
